#!/usr/bin/env node
// validate.js — double-check asset hoặc module sau mỗi tiến trình
// Usage:
//   node validate.js assets/buildings/quan-ca-phe
//   node validate.js threejs-modules/shaders/TriplanarMapping
//
// Features:
//   - Caching: bỏ qua nếu file không đổi kể từ lần PASS trước (hash MD5)
//   - Registry: tự update assets/REGISTRY.json sau mỗi asset PASS
//   - Cache lưu tại .validate-cache.json (gitignored, local-only)

const { execSync } = require('child_process')
const crypto = require('crypto')
const fs = require('fs')
const path = require('path')

// ─── Budget table (từ assets/ROADMAP.md) ─────────────────────────────────────
// Tier đọc từ meta.json field "tier". Default: standard / npc.

const BUDGET = {
  buildings: {
    standard: { tris: 5000,   texturePx: 2048 },
    medium:   { tris: 30000,  texturePx: 2048 },
    hero:     { tris: 100000, texturePx: 4096 },
  },
  props: {
    standard: { tris: 2000, texturePx: 512 },
  },
  characters: {
    npc:  { tris: 15000, texturePx: 1024 },
    hero: { tris: 50000, texturePx: 2048 },
  },
}

// ─── Required meta.json fields per category ───────────────────────────────────

const META_FIELDS = {
  buildings:    ['name', 'category', 'source-tool', 'status', 'description', 'created'],
  props:        ['name', 'category', 'source-tool', 'status', 'description', 'created'],
  characters:   ['name', 'category', 'source-tool', 'status', 'description', 'created', 'rig', 'animations'],
  environments: ['name', 'category', 'source-tool', 'status', 'description', 'created', 'format'],
  textures:     ['name', 'category', 'source', 'resolution', 'maps', 'format', 'license'],
}

const MODULE_META_FIELDS = ['name', 'version', 'category', 'description', 'status', 'dependencies']

// ─── Helpers ──────────────────────────────────────────────────────────────────

let errors = 0

function pass(msg) { console.log(`  ✅ ${msg}`) }
function fail(msg) { console.log(`  ❌ ${msg}`); errors++ }
function warn(msg) { console.log(`  ⚠️  ${msg}`) }

// ─── Cache (skip re-validate nếu files không đổi kể từ lần PASS trước) ───────
// Hash toàn bộ files trong thư mục (tên + nội dung) → MD5 hex string.
// Nếu hash khớp cache → PASS ngay mà không chạy lại, tiết kiệm 30-60s/session.

const CACHE_FILE = path.join(__dirname, '.validate-cache.json')

function hashDir(dirPath) {
  const files = []
  function walk(dir) {
    for (const entry of fs.readdirSync(dir).sort()) {
      const full = path.join(dir, entry)
      if (fs.statSync(full).isDirectory()) walk(full)
      else files.push(full)
    }
  }
  walk(dirPath)
  const h = crypto.createHash('md5')
  for (const f of files) {
    h.update(f.replace(/\\/g, '/'))   // normalize path separator
    h.update(fs.readFileSync(f))
  }
  return h.digest('hex')
}

function loadCache() {
  try { return JSON.parse(fs.readFileSync(CACHE_FILE, 'utf8')) } catch { return {} }
}

function saveCache(cache) {
  fs.writeFileSync(CACHE_FILE, JSON.stringify(cache, null, 2))
}

// ─── Registry (assets/REGISTRY.json — auto-updated sau mỗi asset PASS) ───────
// Upsert entry của asset vào registry tập trung. Không ghi nếu là module.
// Registry giúp scan toàn bộ assets nhanh mà không cần walk thư mục.

function updateRegistry(meta) {
  const registryPath = path.join(__dirname, 'assets', 'REGISTRY.json')
  let reg = { buildings: [], characters: [], environments: [], props: [], textures: [] }
  try { reg = JSON.parse(fs.readFileSync(registryPath, 'utf8')) } catch { /* use default */ }

  const cat = meta.category
  if (!reg[cat]) reg[cat] = []
  reg[cat] = reg[cat].filter(a => a.name !== meta.name)  // xóa entry cũ nếu có
  reg[cat].push({
    name:           meta.name,
    status:         meta.status,
    description:    meta.description,
    tags:           meta.tags || [],
    polycount:      meta.polycount || {},
    'texture-size': meta['texture-size'] || null,
    'file-size':    meta['file-size'] || {},
    bounds:         meta.bounds || null,
    'used-in':      meta['used-in'] || [],
    'last-validated': new Date().toISOString().slice(0, 10),
  })
  reg._meta = {
    note: 'Auto-generated by validate.js — do not edit manually',
    generated: new Date().toISOString(),
  }
  fs.writeFileSync(registryPath, JSON.stringify(reg, null, 2))
  pass('assets/REGISTRY.json đã update')
}

// ─── Asset validator ──────────────────────────────────────────────────────────

function validateAsset(assetPath) {
  // 1. meta.json tồn tại
  const metaPath = path.join(assetPath, 'meta.json')
  if (!fs.existsSync(metaPath)) {
    fail('meta.json không tồn tại')
    return null
  }
  pass('meta.json tồn tại')

  // 2. Parse meta.json
  let meta
  try {
    meta = JSON.parse(fs.readFileSync(metaPath, 'utf8'))
    pass('meta.json hợp lệ JSON')
  } catch (e) {
    fail(`meta.json parse lỗi: ${e.message}`)
    return null
  }

  const category = meta.category
  const folderName = path.basename(assetPath)

  // 3. Required fields theo category
  const required = META_FIELDS[category] || META_FIELDS.buildings
  const missing = required.filter(f => meta[f] === undefined || meta[f] === null || meta[f] === '')
  if (missing.length) {
    fail(`meta.json thiếu fields: ${missing.join(', ')}`)
  } else {
    pass('Tất cả required fields có mặt')
  }

  // 4. Tên folder kebab-case
  if (/^[a-z0-9]+(-[a-z0-9]+)*$/.test(folderName)) {
    pass(`Tên folder kebab-case hợp lệ`)
  } else {
    fail(`Tên folder không đúng kebab-case: "${folderName}"`)
  }

  // 5. meta.name khớp tên folder
  if (meta.name && meta.name !== folderName) {
    fail(`meta.name "${meta.name}" không khớp tên folder "${folderName}"`)
  } else if (meta.name) {
    pass('meta.name khớp tên folder')
  }

  // 6. Status hợp lệ
  const validStatuses = ['raw', 'optimized', 'production']
  if (!validStatuses.includes(meta.status)) {
    fail(`status "${meta.status}" không hợp lệ — phải là: ${validStatuses.join(' / ')}`)
  } else {
    pass(`status "${meta.status}" hợp lệ`)

    // 7. Folder tương ứng với status phải tồn tại
    if (!fs.existsSync(path.join(assetPath, meta.status))) {
      fail(`Folder ${meta.status}/ không tồn tại (status khai báo là "${meta.status}")`)
    } else {
      pass(`Folder ${meta.status}/ tồn tại`)
    }
  }

  // 8. production/ phải có file nếu tồn tại
  const prodPath = path.join(assetPath, 'production')
  if (fs.existsSync(prodPath)) {
    const files = fs.readdirSync(prodPath).filter(f => !f.startsWith('.'))
    if (files.length === 0) {
      fail('production/ folder rỗng — chưa có file browser-ready')
    } else {
      pass(`production/ có ${files.length} file: ${files.join(', ')}`)
    }
  }

  // 9. environments không được có optimized/
  if (category === 'environments' && fs.existsSync(path.join(assetPath, 'optimized'))) {
    fail('environments không cần optimized/ — splat không qua Blender MCP')
  }

  // 10. Budget check (đọc từ meta.json, không cần parse GLB)
  const catBudget = BUDGET[category]
  const tier = meta.tier || (category === 'characters' ? 'npc' : 'standard')
  const budget = catBudget ? (catBudget[tier] ?? null) : null

  if (catBudget && !budget) {
    warn(`tier "${tier}" không hợp lệ cho ${category} — bỏ qua budget check`)
  } else if (budget && meta.polycount?.production) {
    const tris = meta.polycount.production
    if (tris > budget.tris) {
      fail(`Polycount production ${tris.toLocaleString()} vượt budget ${budget.tris.toLocaleString()} (${category}/${tier})`)
    } else {
      pass(`Polycount ${tris.toLocaleString()} trong budget ${tier} (limit: ${budget.tris.toLocaleString()})`)
    }
  } else if (budget && category !== 'environments' && category !== 'textures') {
    warn('polycount.production chưa điền — bỏ qua budget check')
  }

  // 11. texture-size check
  if (meta['texture-size']) {
    const px = parseInt(meta['texture-size'].split('x')[0])
    const limit = budget?.texturePx || 2048
    if (px > limit) {
      fail(`texture-size ${meta['texture-size']} vượt limit ${limit}×${limit} (${category}/${tier})`)
    } else {
      pass(`texture-size ${meta['texture-size']} trong budget`)
    }
  }

  // 12. created date format
  if (meta.created && !/^\d{4}-\d{2}-\d{2}$/.test(meta.created)) {
    fail(`created "${meta.created}" sai format — phải là YYYY-MM-DD`)
  }

  return meta   // trả về để main có thể update registry
}

// ─── Module validator ─────────────────────────────────────────────────────────

function validateModule(modulePath) {
  // 1. Required files
  const requiredFiles = ['index.ts', 'example.ts', 'meta.json', 'README.md']
  for (const file of requiredFiles) {
    if (fs.existsSync(path.join(modulePath, file))) {
      pass(`${file} tồn tại`)
    } else {
      fail(`${file} thiếu`)
    }
  }

  // 2. meta.json fields
  const metaPath = path.join(modulePath, 'meta.json')
  if (fs.existsSync(metaPath)) {
    let meta
    try {
      meta = JSON.parse(fs.readFileSync(metaPath, 'utf8'))
    } catch (e) {
      fail(`meta.json parse lỗi: ${e.message}`)
      return
    }

    const missing = MODULE_META_FIELDS.filter(f => !meta[f] && meta[f] !== 0)
    if (missing.length) {
      fail(`meta.json thiếu fields: ${missing.join(', ')}`)
    } else {
      pass('Tất cả module meta fields có mặt')
    }

    // Dependency existence check — chỉ kiểm tra local module (PascalCase), bỏ qua npm package
    const deps = Array.isArray(meta.dependencies) ? meta.dependencies : []
    const localDeps = deps.filter(dep => /^[A-Z]/.test(dep))
    if (localDeps.length > 0) {
      const tmRoot = modulePath.slice(0, modulePath.indexOf('threejs-modules') + 'threejs-modules'.length)
      const depCategories = ['utils', 'shaders', 'hooks', 'components']
      const missingDeps = localDeps.filter(
        dep => !depCategories.some(cat => fs.existsSync(path.join(tmRoot, cat, dep)))
      )
      if (missingDeps.length) {
        fail(`local dependencies chưa tồn tại trong threejs-modules: ${missingDeps.join(', ')}`)
      } else {
        pass(`Local dependencies tồn tại: ${localDeps.join(', ')}`)
      }
    }
  }

  // 3. index.ts — dispose() pattern
  const indexPath = path.join(modulePath, 'index.ts')
  if (fs.existsSync(indexPath)) {
    const src = fs.readFileSync(indexPath, 'utf8')

    const hasGPU = /new THREE\.(BufferGeometry|ShaderMaterial|RawShaderMaterial|Texture|WebGLRenderTarget)/.test(src)
    const hasDispose = /dispose\s*\(\s*\)\s*[:{]/.test(src)

    if (hasGPU && !hasDispose) {
      fail('Có GPU resource (Geometry/Material/Texture) nhưng thiếu dispose() method')
    } else if (hasGPU) {
      pass('dispose() có mặt (GPU resource detected)')
    }

    // 4. Không dùng `any`
    if (/:\s*any\b/.test(src)) {
      fail('Có dùng TypeScript `any` — vi phạm strict mode')
    } else {
      pass('Không có `any` type')
    }

    // 5. Không inline shader string dài (> 5 dòng = ~150 chars với newlines)
    const inlineShader = /`[^`]{150,}`/.test(src)
    if (inlineShader) {
      fail('Shader string inline dài — phải tách ra file .glsl / .wgsl riêng (import ?raw)')
    } else {
      pass('Không có inline shader string dài')
    }

    // 6. Non-null assertion
    if (/[^!]!\s*[.[]/.test(src)) {
      warn('Có dùng ! non-null assertion — xem xét lại')
    }
  }

  // 7. TypeScript type check — chạy trên toàn bộ threejs-modules/ (không chỉ module này)
  const tmIdx = modulePath.indexOf('threejs-modules')
  const modulesRoot = modulePath.slice(0, tmIdx + 'threejs-modules'.length)
  try {
    execSync('npm run type-check', { cwd: modulesRoot, stdio: 'inherit' })
    pass('TypeScript type check: PASS')
  } catch {
    fail('TypeScript type check: FAIL — xem lỗi ở trên')
  }
}

// ─── Main ─────────────────────────────────────────────────────────────────────

const targetArg = process.argv[2]

if (!targetArg) {
  console.log('Usage:')
  console.log('  node validate.js assets/buildings/quan-ca-phe')
  console.log('  node validate.js threejs-modules/shaders/TriplanarMapping')
  process.exit(0)
}

const resolved = path.resolve(targetArg)

if (!fs.existsSync(resolved)) {
  console.error(`❌ Path không tồn tại: ${resolved}`)
  process.exit(1)
}

// ── Cache check — bỏ qua nếu không có gì thay đổi ────────────────────────────
const cache = loadCache()
const cacheKey = resolved.replace(/\\/g, '/')
const currentHash = hashDir(resolved)

if (cache[cacheKey] === currentHash) {
  console.log(`\n${'─'.repeat(55)}`)
  console.log(`⚡ CACHED: ${path.basename(resolved)} — không đổi, skip validate`)
  console.log(`${'─'.repeat(55)}\n`)
  process.exit(0)
}

// ── Run validation ────────────────────────────────────────────────────────────
const isAsset  = resolved.includes(`${path.sep}assets${path.sep}`)
const isModule = resolved.includes('threejs-modules')

console.log(`\n${'─'.repeat(55)}`)
if (isAsset) {
  console.log(`ASSET CHECK: ${path.basename(resolved)}`)
  console.log('─'.repeat(55))
  const meta = validateAsset(resolved)

  console.log('─'.repeat(55))
  if (errors === 0) {
    cache[cacheKey] = currentHash
    saveCache(cache)
    if (meta) updateRegistry(meta)
    execSync('node update-index.js', { cwd: __dirname, stdio: 'pipe' })
    console.log('✅ PASS — đạt chuẩn, có thể chuyển sang bước tiếp theo\n')
    process.exit(0)
  } else {
    console.log(`❌ FAIL — ${errors} lỗi cần fix trước khi chuyển bước\n`)
    process.exit(1)
  }
} else if (isModule) {
  console.log(`MODULE CHECK: ${path.basename(resolved)}`)
  console.log('─'.repeat(55))
  validateModule(resolved)

  console.log('─'.repeat(55))
  if (errors === 0) {
    cache[cacheKey] = currentHash
    saveCache(cache)
    execSync('node update-index.js', { cwd: __dirname, stdio: 'pipe' })
    console.log('✅ PASS — đạt chuẩn, có thể chuyển sang bước tiếp theo\n')
    process.exit(0)
  } else {
    console.log(`❌ FAIL — ${errors} lỗi cần fix trước khi chuyển bước\n`)
    process.exit(1)
  }
} else {
  console.error('❌ Không xác định được loại — path phải chứa "assets/" hoặc "threejs-modules/"')
  process.exit(1)
}
