#!/usr/bin/env node
// validate-asset.js — kiểm tra asset (GLB, texture, splat) sau Factory pipeline
// Usage: node validate-asset.js assets/buildings/quan-ca-phe
// Cũng được gọi tự động bởi validate.js khi path chứa "assets/"

const { execSync } = require('child_process')
const crypto = require('crypto')
const fs = require('fs')
const path = require('path')

// ─── Budget & field rules (từ assets/ROADMAP.md) ─────────────────────────────

const BUDGET = {
  buildings: {
    standard: { tris: 5000,   texturePx: 2048 },
    medium:   { tris: 30000,  texturePx: 2048 },
    hero:     { tris: 100000, texturePx: 4096 },
  },
  props: {
    standard: { tris: 2000, texturePx: 512 },
  },
  characters: {
    npc:  { tris: 15000, texturePx: 1024 },
    hero: { tris: 50000, texturePx: 2048 },
  },
}

const META_FIELDS = {
  buildings:    ['name', 'category', 'source-tool', 'status', 'description', 'created'],
  props:        ['name', 'category', 'source-tool', 'status', 'description', 'created'],
  characters:   ['name', 'category', 'source-tool', 'status', 'description', 'created', 'rig', 'animations'],
  environments: ['name', 'category', 'source-tool', 'status', 'description', 'created', 'format'],
  textures:     ['name', 'category', 'source', 'resolution', 'maps', 'format', 'license'],
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

let errors = 0
function pass(msg) { console.log('  ✅ ' + msg) }
function fail(msg) { console.log('  ❌ ' + msg); errors++ }
function warn(msg) { console.log('  ⚠️  ' + msg) }

// ─── Cache (shared .validate-cache.json với validate.js) ─────────────────────

const CACHE_FILE = path.join(__dirname, '.validate-cache.json')

function hashDir(dirPath) {
  const files = []
  function walk(dir) {
    for (const entry of fs.readdirSync(dir).sort()) {
      const full = path.join(dir, entry)
      if (fs.statSync(full).isDirectory()) walk(full)
      else files.push(full)
    }
  }
  walk(dirPath)
  const h = crypto.createHash('md5')
  for (const f of files) {
    h.update(f.replace(/\\/g, '/'))
    h.update(fs.readFileSync(f))
  }
  return h.digest('hex')
}

function loadCache() {
  try { return JSON.parse(fs.readFileSync(CACHE_FILE, 'utf8')) } catch { return {} }
}
function saveCache(cache) {
  fs.writeFileSync(CACHE_FILE, JSON.stringify(cache, null, 2))
}

// ─── Registry ─────────────────────────────────────────────────────────────────

function updateRegistry(meta) {
  const registryPath = path.join(__dirname, '..', 'assets', 'REGISTRY.json')
  let reg = { buildings: [], characters: [], environments: [], props: [], textures: [] }
  try { reg = JSON.parse(fs.readFileSync(registryPath, 'utf8')) } catch { /* use default */ }

  const cat = meta.category
  if (!reg[cat]) reg[cat] = []
  reg[cat] = reg[cat].filter(a => a.name !== meta.name)
  reg[cat].push({
    name:             meta.name,
    status:           meta.status,
    description:      meta.description,
    tags:             meta.tags || [],
    polycount:        meta.polycount || {},
    'texture-size':   meta['texture-size'] || null,
    'file-size':      meta['file-size'] || {},
    bounds:           meta.bounds || null,
    'used-in':        meta['used-in'] || [],
    'last-validated': new Date().toISOString().slice(0, 10),
  })
  reg._meta = {
    note:      'Auto-generated by validate-asset.js — do not edit manually',
    generated: new Date().toISOString(),
  }
  fs.writeFileSync(registryPath, JSON.stringify(reg, null, 2))
  pass('assets/REGISTRY.json đã update')
}

// ─── Asset validator ──────────────────────────────────────────────────────────

function validateAsset(assetPath) {
  const metaPath = path.join(assetPath, 'meta.json')
  if (!fs.existsSync(metaPath)) { fail('meta.json không tồn tại'); return null }
  pass('meta.json tồn tại')

  let meta
  try {
    meta = JSON.parse(fs.readFileSync(metaPath, 'utf8'))
    pass('meta.json hợp lệ JSON')
  } catch (e) {
    fail('meta.json parse lỗi: ' + e.message)
    return null
  }

  const category  = meta.category
  const folderName = path.basename(assetPath)

  // Required fields
  const required = META_FIELDS[category] || META_FIELDS.buildings
  const missing  = required.filter(f => meta[f] === undefined || meta[f] === null || meta[f] === '')
  if (missing.length) fail('meta.json thiếu fields: ' + missing.join(', '))
  else pass('Tất cả required fields có mặt')

  // Folder name kebab-case
  if (/^[a-z0-9]+(-[a-z0-9]+)*$/.test(folderName)) pass('Tên folder kebab-case hợp lệ')
  else fail('Tên folder không đúng kebab-case: "' + folderName + '"')

  // meta.name khớp folder
  if (meta.name && meta.name !== folderName)
    fail('meta.name "' + meta.name + '" không khớp tên folder "' + folderName + '"')
  else if (meta.name) pass('meta.name khớp tên folder')

  // Status + folder tương ứng
  const validStatuses = ['raw', 'optimized', 'production']
  if (!validStatuses.includes(meta.status)) {
    fail('status "' + meta.status + '" không hợp lệ — phải là: ' + validStatuses.join(' / '))
  } else {
    pass('status "' + meta.status + '" hợp lệ')
    if (!fs.existsSync(path.join(assetPath, meta.status)))
      fail('Folder ' + meta.status + '/ không tồn tại')
    else pass('Folder ' + meta.status + '/ tồn tại')
  }

  // production/ không rỗng
  const prodPath = path.join(assetPath, 'production')
  if (fs.existsSync(prodPath)) {
    const files = fs.readdirSync(prodPath).filter(f => !f.startsWith('.'))
    if (files.length === 0) fail('production/ folder rỗng — chưa có file browser-ready')
    else pass('production/ có ' + files.length + ' file: ' + files.join(', '))
  }

  // environments không có optimized/
  if (category === 'environments' && fs.existsSync(path.join(assetPath, 'optimized')))
    fail('environments không cần optimized/ — splat không qua Blender MCP')

  // Budget
  const catBudget = BUDGET[category]
  const tier      = meta.tier || (category === 'characters' ? 'npc' : 'standard')
  const budget    = catBudget ? (catBudget[tier] ?? null) : null

  if (catBudget && !budget) {
    warn('tier "' + tier + '" không hợp lệ cho ' + category + ' — bỏ qua budget check')
  } else if (budget && meta.polycount?.production) {
    const tris = meta.polycount.production
    if (tris > budget.tris)
      fail('Polycount ' + tris.toLocaleString() + ' vượt budget ' + budget.tris.toLocaleString() + ' (' + category + '/' + tier + ')')
    else
      pass('Polycount ' + tris.toLocaleString() + ' trong budget ' + tier + ' (limit: ' + budget.tris.toLocaleString() + ')')
  } else if (budget && category !== 'environments' && category !== 'textures') {
    warn('polycount.production chưa điền — bỏ qua budget check')
  }

  // Texture size
  if (meta['texture-size']) {
    const px    = parseInt(meta['texture-size'].split('x')[0])
    const limit = budget?.texturePx || 2048
    if (px > limit)
      fail('texture-size ' + meta['texture-size'] + ' vượt limit ' + limit + '×' + limit + ' (' + category + '/' + tier + ')')
    else
      pass('texture-size ' + meta['texture-size'] + ' trong budget')
  }

  // Created date format
  if (meta.created && !/^\d{4}-\d{2}-\d{2}$/.test(meta.created))
    fail('created "' + meta.created + '" sai format — phải là YYYY-MM-DD')

  return meta
}

// ─── Main ─────────────────────────────────────────────────────────────────────

const targetArg = process.argv[2]
if (!targetArg) {
  console.log('Usage: node validate-asset.js assets/buildings/xyz')
  process.exit(0)
}

const resolved = path.resolve(targetArg)
if (!fs.existsSync(resolved)) {
  console.error('❌ Path không tồn tại: ' + resolved)
  process.exit(1)
}

// Cache check
const cache      = loadCache()
const cacheKey   = resolved.replace(/\\/g, '/')
const currentHash = hashDir(resolved)

if (cache[cacheKey] === currentHash) {
  console.log('\n' + '─'.repeat(55))
  console.log('⚡ CACHED: ' + path.basename(resolved) + ' — không đổi, skip validate')
  console.log('─'.repeat(55) + '\n')
  process.exit(0)
}

console.log('\n' + '─'.repeat(55))
console.log('ASSET CHECK: ' + path.basename(resolved))
console.log('─'.repeat(55))
const meta = validateAsset(resolved)
console.log('─'.repeat(55))

if (errors === 0) {
  cache[cacheKey] = currentHash
  saveCache(cache)
  if (meta) updateRegistry(meta)
  execSync('node update-index.js', { cwd: __dirname, stdio: 'pipe' })
  console.log('✅ PASS — đạt chuẩn, có thể chuyển sang bước tiếp theo\n')
  process.exit(0)
} else {
  console.log('❌ FAIL — ' + errors + ' lỗi cần fix trước khi chuyển bước\n')
  process.exit(1)
}
